5.1:

A.
SELECT E.LAST_NAME, E.SALARY, J.JOB_TITLE
FROM EMPLOYEES E 
JOIN JOBS J
USING(JOB_ID)

B.
SELECT D.DEPARTMENT_NAME, C.COUNTRY_NAME
FROM DEPARTMENTS D
JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID
JOIN COUNTRIES C
ON L.COUNTRY_ID = C.COUNTRY_ID

C.
SELECT C.COUNTRY_NAME, COUNT(D.DEPARTMENT_ID) TOTAL
FROM COUNTRIES C
JOIN LOCATIONS L 
ON C.COUNTRY_ID = L.COUNTRY_ID
JOIN DEPARTMENTS D 
ON L.LOCATION_ID = D.LOCATION_ID
GROUP BY C.COUNTRY_ID, C.COUNTRY_NAME

D.
SELECT E.EMPLOYEE_ID, COUNT(*)
FROM EMPLOYEES E
JOIN JOB_HISTORY J 
ON E.EMPLOYEE_ID = J.EMPLOYEE_ID
GROUP BY E.EMPLOYEE_ID

E.
SELECT D.DEPARTMENT_NAME, J.JOB_TITLE, COUNT(*)
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN JOBS J
ON J.JOB_ID = E.JOB_ID
GROUP BY D.DEPARTMENT_NAME, J.JOB_TITLE

F.
SELECT E1.LAST_NAME, COUNT(E2.EMPLOYEE_ID) HIRED_BEFORE
FROM EMPLOYEES E1
LEFT JOIN EMPLOYEES E2
ON E1.HIRE_DATE > E2.HIRE_DATE
GROUP BY E1.EMPLOYEE_ID, E1.LAST_NAME

G.
SELECT E1.LAST_NAME, COUNT(DISTINCT E2.EMPLOYEE_ID) HIRED_BEFORE, COUNT(DISTINCT E3.EMPLOYEE_ID) HIRED_AFTER
FROM EMPLOYEES E1
LEFT JOIN EMPLOYEES E2
ON E1.HIRE_DATE > E2.HIRE_DATE
LEFT JOIN EMPLOYEES E3
ON E1.HIRE_DATE < E3.HIRE_DATE
GROUP BY E1.EMPLOYEE_ID, E1.LAST_NAME

H.
SELECT E1.LAST_NAME, COUNT(E2.EMPLOYEE_ID) MORE_THAN
FROM EMPLOYEES E1
JOIN EMPLOYEES E2
ON E1.SALARY > E2.SALARY
GROUP BY E1.EMPLOYEE_ID, E1.LAST_NAME
HAVING COUNT(E2.EMPLOYEE_ID) >= 3

I.
SELECT E1.LAST_NAME, E1.SALARY, COUNT(DISTINCT E2.EMPLOYEE_ID) + 1 RANK
FROM EMPLOYEES E1
LEFT JOIN EMPLOYEES E2
ON E1.SALARY < E2.SALARY
GROUP BY E1.EMPLOYEE_ID, E1.LAST_NAME, E1.SALARY
ORDER BY E1.SALARY DESC

J.
SELECT E.LAST_NAME, E.SALARY
FROM EMPLOYEES E
JOIN (
    SELECT DISTINCT SALARY
    FROM EMPLOYEES
    ORDER BY SALARY DESC
    FETCH FIRST 3 ROWS ONLY
) T ON E.SALARY = T.SALARY
ORDER BY E.SALARY DESC, E.LAST_NAME

6.1

A.
SELECT
  LAST_NAME 
FROM
  EMPLOYEES 
WHERE
  DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE UPPER(DEPARTMENT_NAME) = 'SALES')
  
  B.
  SELECT
  LAST_NAME,
  SALARY 
FROM
  EMPLOYEES 
WHERE
  SALARY > ANY (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE UPPER(DEPARTMENT_NAME) = 'SALES'))
  
  C.
  SELECT
  LAST_NAME,
  SALARY 
FROM
  EMPLOYEES 
WHERE
  SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE UPPER(DEPARTMENT_NAME) = 'SALES'))
  
  D.
  SELECT
  LAST_NAME,
  SALARY 
FROM
  EMPLOYEES 
WHERE
  SALARY BETWEEN
  (SELECT MIN(SALARY)
  FROM EMPLOYEES
  WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE UPPER(DEPARTMENT_NAME) = 'SALES')) - 5000
  AND
  (SELECT MAX(SALARY)
  FROM EMPLOYEES
  WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE UPPER(DEPARTMENT_NAME) = 'SALES')) + 5000
  
  6.2
  
  A.
  SELECT
  LAST_NAME,
  SALARY 
FROM
  EMPLOYEES E1 
WHERE
  3 <= (SELECT COUNT(E2.EMPLOYEE_ID) FROM EMPLOYEES E2 WHERE E2.SALARY < E1.SALARY)
  
B.
SELECT DEPARTMENT_NAME
FROM DEPARTMENTS D
WHERE (
SELECT AVG(E1.SALARY)
FROM EMPLOYEES E1
WHERE E1.DEPARTMENT_ID = D.DEPARTMENT_ID)
> ALL (
SELECT MIN(E2.SALARY)
FROM EMPLOYEES E2
WHERE E2.DEPARTMENT_ID <> D.DEPARTMENT_ID
GROUP BY E2.DEPARTMENT_ID
)

C.
SELECT DEPARTMENT_NAME
FROM DEPARTMENTS D
WHERE (
SELECT COUNT(*)
FROM EMPLOYEES E
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID)
= (
SELECT MAX(DEPT_COUNT)
FROM  (
SELECT COUNT(*) DEPT_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID))

D.
SELECT EMPLOYEE_ID, LAST_NAME
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (
SELECT EMPLOYEE_ID
FROM JOB_HISTORY
GROUP BY EMPLOYEE_ID
HAVING COUNT(DEPARTMENT_ID) > 1 )

E.
SELECT E.LAST_NAME, D.MINSAL, D.MAXSAL
FROM EMPLOYEES E, (
SELECT DEPARTMENT_ID, MIN(SALARY) MINSAL, MAX(SALARY) MAXSAL
FROM EMPLOYEES 
GROUP BY DEPARTMENT_ID) D 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID

F.
SELECT J.JOB_TITLE, E.LAST_NAME
FROM JOBS J, EMPLOYEES E
WHERE E.JOB_ID = J.JOB_ID
AND E.SALARY = (
SELECT MAX(SALARY)
FROM EMPLOYEES E2
WHERE E2.JOB_ID = E.JOB_ID)

7.1

A.
SELECT EMPLOYEE_ID
FROM EMPLOYEES
MINUS 
SELECT MANAGER_ID 
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL

B.
SELECT LAST_NAME
FROM EMPLOYEES
MINUS 
SELECT LAST_NAME
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (
SELECT MANAGER_ID 
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL)

C.
SELECT LOCATION_ID
FROM LOCATIONS
MINUS 
SELECT LOCATION_ID
FROM DEPARTMENTS
WHERE LOCATION_ID IS NOT NULL

11.3

A.
SELECT DEPARTMENT_ID,
  COUNT(CASE WHEN SALARY > 15000 THEN 1 END) AS "A+",
  COUNT(CASE WHEN SALARY >= 10000 AND SALARY < 15000 THEN 1 END) AS "A",
  COUNT(CASE WHEN SALARY >= 5000 AND SALARY < 10000 THEN 1 END) AS "B",
  COUNT(CASE WHEN SALARY < 5000 THEN 1 END) AS "C"
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID ASC;

B.
SELECT DEPARTMENT_ID,
  COUNT(DECODE(SIGN(SALARY - 15000), 1, 1)) AS "A+",
  COUNT(DECODE(SIGN(SALARY - 10000), 1, NULL, DECODE(SIGN(SALARY - 15000), -1, 1))) AS "A",
  COUNT(DECODE(SIGN(SALARY - 5000), 1, NULL, DECODE(SIGN(SALARY - 10000), -1, 1))) AS "B",
  COUNT(DECODE(SIGN(SALARY - 5000), -1, 1)) AS "C"
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;

C.
SELECT 
  E.EMPLOYEE_ID,
  E.LAST_NAME,
  E.DEPARTMENT_ID,
  E.MANAGER_ID,
  D1.DEPT_EMP_COUNT AS EMP_DEPT_COUNT,
  D2.MGR_DEPT_EMP_COUNT AS MGR_DEPT_COUNT
FROM 
  EMPLOYEES E
LEFT JOIN (
  SELECT DEPARTMENT_ID, COUNT(*) AS DEPT_EMP_COUNT
  FROM EMPLOYEES
  GROUP BY DEPARTMENT_ID
) D1
  ON E.DEPARTMENT_ID = D1.DEPARTMENT_ID
LEFT JOIN (
  SELECT MGR.DEPARTMENT_ID, COUNT(*) AS MGR_DEPT_EMP_COUNT
  FROM EMPLOYEES EMP
  JOIN EMPLOYEES MGR ON EMP.MANAGER_ID = MGR.EMPLOYEE_ID
  GROUP BY MGR.DEPARTMENT_ID
) D2
  ON E.MANAGER_ID IS NOT NULL AND D2.DEPARTMENT_ID = (
    SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = E.MANAGER_ID
  )