-- 1

SELECT
    E.EMPLOYEE_ID,
    E.FIRST_NAME || ' ' || E.LAST_NAME AS FULL_NAME,
    D.DEPARTMENT_NAME,
    E.SALARY
FROM
    EMPLOYEES E
    JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE (
    SELECT COUNT(DISTINCT E2.SALARY)
    FROM EMPLOYEES E2
    JOIN DEPARTMENTS D2 ON E2.DEPARTMENT_ID = D2.DEPARTMENT_ID
    WHERE D2.LOCATION_ID = D.LOCATION_ID
      AND E2.DEPARTMENT_ID != E.DEPARTMENT_ID
      AND E.SALARY > E2.SALARY
) >= 5
ORDER BY
    D.DEPARTMENT_NAME DESC,
    E.SALARY DESC,
    E.EMPLOYEE_ID ASC;
    
    -- 2
    
    SELECT
    D.DEPARTMENT_NAME,
    M.FIRST_NAME || ' ' || M.LAST_NAME AS MANAGER_NAME,
    M.SALARY
FROM
    DEPARTMENTS D
    JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
    JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
    JOIN REGIONS R ON C.REGION_ID = R.REGION_ID
    JOIN EMPLOYEES M ON D.MANAGER_ID = M.EMPLOYEE_ID
WHERE
    R.REGION_NAME = 'Americas'
    AND M.SALARY BETWEEN 10000 AND 15000
    AND D.DEPARTMENT_ID IN (
        SELECT DEPARTMENT_ID
        FROM EMPLOYEES
        GROUP BY DEPARTMENT_ID
        HAVING COUNT(*) >= 2
    )
ORDER BY
    M.SALARY DESC,
    D.DEPARTMENT_NAME ASC;
    
    -- 3
    
    WITH
DEPT_JOBS AS (
    SELECT DEPARTMENT_ID, COUNT(DISTINCT JOB_ID) AS TOTAL_JOBS
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID
),
EMP_JOB_HISTORY AS (
    SELECT H.EMPLOYEE_ID, H.DEPARTMENT_ID, COUNT(DISTINCT H.JOB_ID) AS JOBS_HELD
    FROM JOB_HISTORY H
    GROUP BY H.EMPLOYEE_ID, H.DEPARTMENT_ID
),
MATCHED_DEPTS AS (
    SELECT DJ.DEPARTMENT_ID
    FROM DEPT_JOBS DJ
    JOIN EMP_JOB_HISTORY EJH
      ON DJ.DEPARTMENT_ID = EJH.DEPARTMENT_ID
     AND DJ.TOTAL_JOBS = EJH.JOBS_HELD
    GROUP BY DJ.DEPARTMENT_ID
),
COMPANY_AVG AS (
    SELECT AVG(SALARY) AS AVG_SAL FROM EMPLOYEES
),
DEPT_AVG AS (
    SELECT DEPARTMENT_ID, AVG(SALARY) AS AVG_SAL FROM EMPLOYEES GROUP BY DEPARTMENT_ID
)
SELECT
    D.DEPARTMENT_NAME,
    CASE
        WHEN DA.AVG_SAL > CA.AVG_SAL THEN 'ABOVE'
        ELSE 'BELOW'
    END AS SALARY_COMPARISON
FROM MATCHED_DEPTS MD
JOIN DEPARTMENTS D ON MD.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN DEPT_AVG DA ON D.DEPARTMENT_ID = DA.DEPARTMENT_ID
CROSS JOIN COMPANY_AVG CA;

-- 4

WITH
    AVG_SAL AS (
        SELECT AVG(SALARY) AS AVG_SAL FROM EMPLOYEES
    ),
    MULTI_DEPT_MANAGER AS (
        SELECT MANAGER_ID
        FROM EMPLOYEES
        WHERE MANAGER_ID IS NOT NULL
        GROUP BY MANAGER_ID
        HAVING COUNT(DISTINCT DEPARTMENT_ID) > 1
    ),
    SEATTLE_DEPT AS (
        SELECT D.DEPARTMENT_ID
        FROM DEPARTMENTS D
        JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
        WHERE L.CITY = 'Seattle'
    )
SELECT
    E.EMPLOYEE_ID,
    E.FIRST_NAME,
    E.LAST_NAME,
    CASE
        WHEN E.EMPLOYEE_ID IN (SELECT MANAGER_ID FROM MULTI_DEPT_MANAGER)
             THEN 'Multi-Dept Manager'
        ELSE 'Above Avg Salary'
    END AS TYPE
FROM EMPLOYEES E
CROSS JOIN AVG_SAL A
WHERE (
    E.EMPLOYEE_ID IN (SELECT MANAGER_ID FROM MULTI_DEPT_MANAGER)
    OR E.SALARY > A.AVG_SAL
)
AND E.DEPARTMENT_ID NOT IN (SELECT DEPARTMENT_ID FROM SEATTLE_DEPT);

-- 5
SELECT
    D.DEPARTMENT_NAME,
    E.EMPLOYEE_ID,
    E.SALARY
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.SALARY = (
    SELECT MAX(E2.SALARY)
    FROM EMPLOYEES E2
    WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID
)
ORDER BY
    E.SALARY DESC,
    D.DEPARTMENT_NAME DESC,
    E.EMPLOYEE_ID ASC;