--1

SELECT
  c.COUNTRY_ID,
  COUNT( l.city ) number_of_cities,
  COUNT( l.STATE_PROVINCE ) "number of provinces" 
FROM
  COUNTRIES c,
  LOCATIONS l 
WHERE
  c.COUNTRY_ID = l.COUNTRY_ID 
GROUP BY
  c.COUNTRY_ID 
HAVING
  COUNT( l.STATE_PROVINCE ) <> 0 
  AND COUNT( l.city ) >= 2 
ORDER BY
  c.COUNTRY_ID ASC;

--2
SELECT
  DEPARTMENT_ID 
FROM
  JOB_HISTORY 
WHERE
  START_DATE - END_DATE <= 600 
GROUP BY
  DEPARTMENT_ID 
HAVING
  COUNT( * ) <=1

--3
SELECT
  COALESCE( DEPARTMENT_ID, 0 ),
  MIN( HIRE_DATE ) minimum_hire_date,
  MAX( HIRE_DATE ) maximum_hire_date,
  AVG( COALESCE(SALARY, 0) ) average_salary 
FROM
  EMPLOYEES 
GROUP BY
  DEPARTMENT_ID 
ORDER BY
  ( MAX( HIRE_DATE ) - MIN( HIRE_DATE ) ) ASC,
  AVG( SALARY ) DESC

--4
SELECT
  FIRST_NAME || ' ' || LAST_NAME FULL_NAME,
  SALARY * 12 ANN_SAL,
  SALARY MON_SAL,
  COMMISSION_PCT,
  SALARY + ( ( SALARY * 12 * NVL( COMMISSION_PCT,- 0.0005 ) ) / 100 ) INCMNT 
FROM
  EMPLOYEES

--5
SELECT
  MANAGER_ID,
  COUNT( * ),
  TRUNC( AVG( SALARY ) ) 
FROM
  EMPLOYEES 
WHERE
  EXTRACT( MONTH FROM HIRE_DATE ) IN ( 3, 9, 12 ) 
GROUP BY
  MANAGER_ID 
ORDER BY
  COUNT( * ) ASC,
  AVG( SALARY ) DESC